spring:
  application:
    name: auth-registry-service
  data:
    mongodb:
      uri: mongodb://admin:auth-service@localhost:27017/auth-service?authSource=admin
  redis:
    host: localhost
    port: 6379
    password: auth-service

service-shared-secret: world
customer-auth-signing-secret: world
ignore-post-paths: /user, /user/redefine-password/code, /user/redefine-password,  /auth/login
ignore-put-paths: /user/update-password
ignore-get-paths: /user/redefine-password/**

session-expiration: 2
redefine-password-code-expiration: 5
customer-auth-expiration-token: 24

communication:
  url: http://localhost:8081
  service-shared: world
  email:
    location-template: communication-d-1/emails/
    redefine-password-template: password-reset.html
    password-updated-template: password-updated.html
    welcome-template: welcome.html
    new-access-template: new-access.html

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /api-docs.yml